
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sales_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'sales_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring seeds
seeds:
  sales_analytics:
    special_offer:
      file: "special_offer.csv"  # Specify the name of your CSV file here
      delimiter: ","             # The delimiter for the CSV file (default is comma)
      header: true               # Ensure the first row is treated as header (default is true)
    
    product_category:
      file: "product_category.csv"  # Specify the name of your Product_Category CSV file
      delimiter: ","               # The delimiter for the CSV file (default is comma)
      header: true   
      
    product_subcategory:
      file: "product_subcategory.csv"  # Specify the name of your Product_Subcategory CSV file
      delimiter: ","                 # The delimiter for the CSV file (default is comma)
      header: true 


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  sales_analytics:
    # Config indicated by + and applies to all files under models/example/
      +materialized: view

           